### ISSUE TITLE
media panel: cannot scroll albums and squeezed ablum browser

### ISSUE THREAD

**Issue by nicman23** [arfbtwn/banshee#54]
tested on wheel, touchpad and trackpoint..

if i resize the window then it works. On opening the window the whole album browser seems squeezed together

before resize

![screenshot_20171008_140751](https://user-images.githubusercontent.com/16306097/31316224-18e03172-ac32-11e7-96c6-98320b353180.png)

after resize

![screenshot_20171008_140839](https://user-images.githubusercontent.com/16306097/31316235-36959108-ac32-11e7-9e59-f68b964e8c82.png)

**Comment by arfbtwn** [comment]
would you mind testing the patch from #63 for me? It's the last subproject update commit that should correct this issue.

**Comment by arfbtwn** [comment]
would be cool to get a second pair of eyes on #58 too - fix for that is included in the #63 branch so you should be able to merge that into `feature/mediapanel` in your build script

**Comment by nicman23** [comment]
- it is fine in feature/lite, broken on feature/mediapanel
- banshee --classic does not display the old ui with feature/lite with the --enable-treeview
- sorry i do not use podcasts :C 

(everything on latest commit per branch)

**Comment by arfbtwn** [comment]
hang on, what issue are you talking about? Try and keep discussion to the right issue so I don't get confused.

If you merge `feature/browser` into `feature/mediapanel` you should get this fix. Fair enough if you don't use podcasts :+1:

**Comment by nicman23** [comment]
oups, sorry i got confused as well because you asked in the previous comment about #58...

also you have already merged everything in features/lite as i can see.

again this bug is fixed

**Comment by arfbtwn** [comment]
ah, so you're using `feature/lite`, that might be a tricky branch to follow as it's rebased a lot - it's still experimental. :)

Re-opening until #63 is merged.

**Comment by arfbtwn** [comment]
I've been testing some patches with `master` branch and the inability to scroll is definitely still present, re-opening until I find a fix for that. Browser squashing seems solved though.

**Comment by arfbtwn** [comment]
Fix merged to master
